language: php
dist: trusty

php:
  - 7.3.0

install:
  - composer install

script:
  - vendor/bin/phpcs --standard=PSR2 ./src/
  - vendor/bin/phpstan analyse -l max src --no-interaction --no-progress

after_success:
  - bash <(curl -s https://codecov.io/bash)
